/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PAccordion: typeof import('primevue/accordion')['default']
    PAccordionContent: typeof import('primevue/accordioncontent')['default']
    PAccordionHeader: typeof import('primevue/accordionheader')['default']
    PAccordionPanel: typeof import('primevue/accordionpanel')['default']
    PAvatar: typeof import('primevue/avatar')['default']
    PButton: typeof import('primevue/button')['default']
    PCard: typeof import('primevue/card')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PDrawer: typeof import('primevue/drawer')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMenu: typeof import('primevue/menu')['default']
    PSelect: typeof import('primevue/select')['default']
    PSkeleton: typeof import('primevue/skeleton')['default']
    PTab: typeof import('primevue/tab')['default']
    PTabList: typeof import('primevue/tablist')['default']
    PTabPanel: typeof import('primevue/tabpanel')['default']
    PTabPanels: typeof import('primevue/tabpanels')['default']
    PTabs: typeof import('primevue/tabs')['default']
    PToast: typeof import('primevue/toast')['default']
    PToggleSwitch: typeof import('primevue/toggleswitch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
